"""Analysis helpers for future Priority 0 observations."""

from viewtrust.analysis.offline_signals import (
    compute_ablation_metrics,
    compute_group_metrics,
    compute_signal_components,
    mad,
    positive_part,
    precision_at_k,
    rank_descending,
    recall_at_k,
    robust_median,
    robust_z_scores,
    safe_divide,
    safe_float,
)
from viewtrust.analysis.offline_multi_condition import (
    aggregate_condition_results,
    compute_condition_ranking,
    compute_failure_cases,
    condition_result_from_signal_dir,
    discover_offline_signal_dirs,
    validate_offline_signal_dir,
)
from viewtrust.analysis.offline_rank_consistency import (
    build_component_condition_summary,
    build_component_gap_table,
    build_component_win_table,
    build_corrupted_view_rank_distribution,
    build_cross_condition_view_rank_table,
    build_false_positive_topk_views,
    build_repeated_top_views,
    build_summary_json,
    find_condition_signal_dir,
    write_artifact_manifest,
    write_rank_consistency_report,
)
from viewtrust.analysis.subset_scene_bias import (
    build_condition_matrix,
    build_pr16_summary,
    build_scene_bias_summary,
    build_scene_subset_condition_results,
    build_subset_bias_summary,
    build_subset_manifest,
    build_view_identity_bias_table,
    discover_pr16_condition_output,
    discover_train_views,
    generate_seeded_subset,
    stable_hash_view_list,
)
from viewtrust.analysis.statistics import NumericSummary, summarize_numbers, summarize_table
from viewtrust.analysis.tables import write_csv_table

__all__ = [
    "NumericSummary",
    "aggregate_condition_results",
    "build_component_condition_summary",
    "build_component_gap_table",
    "build_component_win_table",
    "build_corrupted_view_rank_distribution",
    "build_cross_condition_view_rank_table",
    "build_false_positive_topk_views",
    "build_repeated_top_views",
    "build_summary_json",
    "build_condition_matrix",
    "build_pr16_summary",
    "build_scene_bias_summary",
    "build_scene_subset_condition_results",
    "build_subset_bias_summary",
    "build_subset_manifest",
    "build_view_identity_bias_table",
    "compute_condition_ranking",
    "compute_failure_cases",
    "compute_ablation_metrics",
    "compute_group_metrics",
    "compute_signal_components",
    "condition_result_from_signal_dir",
    "discover_offline_signal_dirs",
    "discover_pr16_condition_output",
    "discover_train_views",
    "find_condition_signal_dir",
    "generate_seeded_subset",
    "mad",
    "positive_part",
    "precision_at_k",
    "rank_descending",
    "recall_at_k",
    "robust_median",
    "robust_z_scores",
    "safe_divide",
    "safe_float",
    "stable_hash_view_list",
    "summarize_numbers",
    "summarize_table",
    "validate_offline_signal_dir",
    "write_artifact_manifest",
    "write_csv_table",
    "write_rank_consistency_report",
]
